name: Publish QMod

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true

    - uses: BobbyShmurner/mod-uploader@main
      with:
        qmod-url: 'https://github.com/BobbyShmurner/ThiccSaber/releases/download/v1.0.0/ThiccSaber_v1.0.0.qmod'
        mod-json: 'mod.json'
        token: '${{ secrets.GITHUB_TOKEN }}'
        repo-token: '${{ secrets.REPO_ACCESS }}'